# Generated by Django 3.1.5 on 2021-01-13 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='departamento_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='migrate_01.departamento'),
        ),
    ]
