# Generated by Django 3.1.4 on 2021-01-14 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_01', '0002_auto_20210113_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('patente', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='profesor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='migrate_01.profesor'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('asignatura_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrate_01.asignatura')),
                ('profesor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrate_01.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombre', models.CharField(max_length=35)),
                ('Edad', models.IntegerField()),
                ('run', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrate_01.curso')),
                ('transportista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrate_01.transportista')),
            ],
        ),
    ]
