# Generated by Django 3.1.4 on 2021-01-14 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_01', '0003_auto_20210114_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='migrate_01.profesor'),
        ),
    ]
