# Generated by Django 3.1.4 on 2021-01-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('migrate_01', '0004_auto_20210114_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['id']},
        ),
    ]
